[binaries]
c = ['zig', 'cc']
cpp = ['zig', 'c++']
ar = ['zig', 'ar']
ranlib = ['zig', 'ranlib']
lib = ['zig', 'lib']
dlltool = ['zig', 'dlltool']
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'loongarch64'
cpu = 'loongarch64'
endian = 'little'

[built-in options]
c_args = ['-target', 'loongarch64-linux-gnu']
c_link_args = ['-target', 'loongarch64-linux-gnu']
