name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up QEMU (for cross-compilation)
        if: matrix.system != 'x86_64-linux'
        uses: docker/setup-qemu-action@v3

      - name: Build for ${{ matrix.system }}
        run: |
          nix build --system ${{ matrix.system }} .#default
          
      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp result/bin/zzz dist/zzz-${{ matrix.system }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zzz-${{ matrix.system }}
          path: dist/zzz-${{ matrix.system }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/zzz-x86_64-linux/zzz-x86_64-linux
            artifacts/zzz-aarch64-linux/zzz-aarch64-linux
            artifacts/zzz-armv7l-linux/zzz-armv7l-linux
            artifacts/zzz-mipsel-linux/zzz-mipsel-linux
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
